version: '3'
services:
  database:
    container_name: postgres
    image: library/postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: navstatus
      POSTGRES_USERNAME: postgres
      PGTZ: Europe/Oslo
  backend:
    container_name: javabackend
    image: statusplattform-backend:default
    environment:
      teamkatalogApiUrl: https://teamkatalog-api.intern.dev.nav.no
      swagger-api-key: key
      DB_USERNAME: postgres
      DB_PORT: 5432
      DB_HOSTNAME: database
      FRONTEND_LOCATION: 'placeholder'
      TENANT: trygdeetaten.no
      AZURE_APP_CLIENT_ID: foo
      AZURE_APP_CLIENT_SECRET: bar
      ENV: dev # TODO will be replaced by scope
    depends_on:
      - database
  frontend:
    container_name: reactfrontend
    build:
      context: .
      args:
        NPM_AUTH_TOKEN:
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKENDPATH: http://backend:3005
    depends_on:
      - backend
