apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: portal
    namespace: navdig
    labels:
        team: navdig
spec:
    image: {{ image }}
    port: 3000
    ingresses:
        - https://status.intern.dev.nav.no/sp
        #image: ghcr.io/navikt/myapplication:417dcaa2c839b9da72e0189e2cfdd4e90e9cc6fd
        #       ^--- interpolated from the ${{ env.docker_image }} variable in the action
    env:
        - name: NEXT_PUBLIC_BACKENDPATH
          value: "http://portalserver"
        - name: NEXT_PUBLIC_APPROVED_USERS
          value: "L152423,H161540,K146221,J104568,G124938,M106261,M137316,G121973,H166137"
        - name: NEXT_PUBLIC_OPS_ACCESS
          value: "L152423,K132081,H123099,L110875,K125327,F110862,A110886,L120166,M106261,M137316,G121973,H166137"
        - name: NPM_CONFIG_CACHE
          value: /tmp
        - name: TENANT
          value: nav.no
        - name: ENV
          value: dev
    replicas:
        min: 1
        max: 1
    azure:
        application:
            enabled: true
            tenant: nav.no
            claims:
                extra:
                    - "NAVident"
                    - "azp_name"
            # optional, defaults shown
            singlePageApplication: false
            allowAllUsers: true
        sidecar:
            enabled: true
            autoLogin: false
            errorPath: ""
    accessPolicy:
        outbound:
            rules:
                - application: portalserver
