apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: portal
    namespace: navdig
    labels:
        team: navdig
spec:
    image: { { image } }
    port: 3000
    ingresses:
        - https://portal.labs.nais.io
    #image: ghcr.io/navikt/myapplication:417dcaa2c839b9da72e0189e2cfdd4e90e9cc6fd
    #       ^--- interpolated from the ${{ env.docker_image }} variable in the action
