apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: portal
    namespace: navdig
    labels:
        team: navdig
spec:
    image: {{ image }}
    port: 3000
    ingresses:
        - https://status.dev.nav.no/sp
        #image: ghcr.io/navikt/myapplication:417dcaa2c839b9da72e0189e2cfdd4e90e9cc6fd
        #       ^--- interpolated from the ${{ env.docker_image }} variable in the action
    env:
        - name: ENVIRONMENT
          value: "dev"
    replicas:
        min: 1
        max: 1
    azure:
        application:
            enabled: true
            # optional, enum of {trygdeetaten.no, nav.no}
            # defaults to trygdeetaten.no in dev-* clusters, nav.no in production
            tenant: nav.no
            # optional
            replyURLs:
                - "https://status.dev.nav.no/sp/oauth2/callback"
                - "https://status.dev.nav.no/sp/Dashboard/Privatperson"
            claims:
                extra:
                    - "NAVident"
                    - "azp_name"
            # optional, defaults shown
            singlePageApplication: false
        sidecar:
            enabled: true
            autoLogin: true
            errorPath: ""
