name: Build, push, and deploy

on: [push]

env:
    docker_image: ghcr.io/navikt/${{ github.repository }}:${{ github.sha }}

jobs:
    build-and-push:
        name: Build and push Docker container
        runs-on: ubuntu-latest
        permissions:
            packages: write
        steps:
            - uses: actions/checkout@v4
            
            - name: Build and push docker image to GAR
              uses: nais/docker-build-push@main
              id: docker-push
              with:
                target: runtime
                team: navdig
                project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
                identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                build_secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}

    deploy-test:
        name: Deploy application to test env
        needs: build-and-push
        if: github.ref == 'refs/heads/develop'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: nais/deploy/actions/deploy@v2
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  RESOURCE: nais-test.yml
                  VAR: image=${{ env.docker_image }}

    deploy-prod:
        name: Deploy application to prod
        needs: build-and-push
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: nais/deploy/actions/deploy@v2
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: nais.yml
                  VAR: image=${{ env.docker_image }}
