name: Build, push, and deploy

on: [push]

permissions:
    contents: read
    id-token: write
    packages: write
jobs:
    build:
        name: Build and push Docker container
        runs-on: ubuntu-latest
        outputs:
         image: ${{ steps.docker-push.outputs.image }}
        steps:
            - uses: actions/checkout@v4
            
            - name: Build and push docker image to GAR
              uses: nais/docker-build-push@main
              id: docker-push
              with:
                team: navdig
                project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
                identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                build_secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}

    deploy-test:
        name: Deploy application to test env
        needs: build
        if: github.ref == 'refs/heads/develop'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: nais/deploy/actions/deploy@v2
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  RESOURCE: nais-test.yml
                  VAR: image=${{ needs.build.outputs.image }}


    deploy-prod:
        name: Deploy application to prod
        needs: build
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: nais/deploy/actions/deploy@v2
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: nais.yml
                  VAR: image=${{ needs.build.outputs.image }}
